// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package ebsdirect

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	AMIName        *string           `mapstructure:"ami_name" cty:"ami_name" hcl:"ami_name"`
	AMIDescription *string           `mapstructure:"ami_description" cty:"ami_description" hcl:"ami_description"`
	Architecture   *string           `mapstructure:"architecture" cty:"architecture" hcl:"architecture"`
	BootMode       *string           `mapstructure:"boot_mode" cty:"boot_mode" hcl:"boot_mode"`
	RootDeviceName *string           `mapstructure:"root_device_name" cty:"root_device_name" hcl:"root_device_name"`
	Region         *string           `mapstructure:"region" cty:"region" hcl:"region"`
	Tags           map[string]string `mapstructure:"tags" cty:"tags" hcl:"tags"`
	SnapshotTags   map[string]string `mapstructure:"snapshot_tags" cty:"snapshot_tags" hcl:"snapshot_tags"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"ami_name":         &hcldec.AttrSpec{Name: "ami_name", Type: cty.String, Required: false},
		"ami_description":  &hcldec.AttrSpec{Name: "ami_description", Type: cty.String, Required: false},
		"architecture":     &hcldec.AttrSpec{Name: "architecture", Type: cty.String, Required: false},
		"boot_mode":        &hcldec.AttrSpec{Name: "boot_mode", Type: cty.String, Required: false},
		"root_device_name": &hcldec.AttrSpec{Name: "root_device_name", Type: cty.String, Required: false},
		"region":           &hcldec.AttrSpec{Name: "region", Type: cty.String, Required: false},
		"tags":             &hcldec.AttrSpec{Name: "tags", Type: cty.Map(cty.String), Required: false},
		"snapshot_tags":    &hcldec.AttrSpec{Name: "snapshot_tags", Type: cty.Map(cty.String), Required: false},
	}
	return s
}
